### PR TITLE
Chore: icons to issue templates + fix typos/phrasing

### PR DESCRIPTION
**Pull request by hzierer**
## Description

Thanks for opening this contribution!
_What does this PR introduce? Does it fix a bug? Does it add a new feature? Is it enhancing documentation?_

- adds icons to the overview of the issue templates
- Fixes some minor typos + changed phrasing of the EF link description

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
LGTM

**Review by carslen — COMMENTED** [review]
I'm not a fan of this and I can't see added value there except of adding some sort of "bling bling" to the issue types. For me the argument "it helps identifying the correct issue type" isn't valid or strong enough. Interpreting the emojis can be harder than reading the issue type description (or how ever this is called) here.

I'm more a fan of the KISS principle. The rows in our project board has icons, each issue has assigned one or more colorful labels and now the issue title itself will show an additional icon? Looking into our project board will then look more like a candy shop...

If GH introduces adding GIFs to the title, will we implement it, just because it's possible?

**Comment by FaGru3n** [comment]
>  issue title itself will show an additional icon

FYI @carslen the icons for the issue template will not be shown in the title of the issue itself, it will update this view
image

**Comment by FaGru3n** [comment]
> The rows in our project board has icons

which one you want to remove?
https://github.com/orgs/eclipse-tractusx/projects/9/settings/fields/Status

all of the icons in the swimlanes?

**Comment by carslen** [comment]
Thanks for clarification :)

**Comment by carslen** [comment]
> > The rows in our project board has icons
> 
> which one you want to remove? https://github.com/orgs/eclipse-tractusx/projects/9/settings/fields/Status
> 
> all of the icons in the swimlanes?

I don't want to remove them but I want to avoid additional overloading.

**Comment by hzierer** [comment]
Alternatively we could add only 3 different icons: one for security, one for system team and the last for EF.

My intention is to visually separate the templates somehow. To be honest, horizontal lines would be perfect too, but I found no solution for that

**Comment by hzierer** [comment]
too little interest... - closing it

**Pull request closed without merging**
