### PR TITLE
Update legal docs (TRG7)

### PR DESCRIPTION
**Pull request by AngelikaWittek**
## Description

Updates due to (upcoming) changes in TRG 7:

- added Terms of Use in CONTRIBUTING file
- extended NOTICE file with a notice for the CC-BY-4.0 license
- added the CC-BY-4.0 license to the root repository as default license for non-code artifacts

## Pre-review checks

Not necessary for the changes.

### CODE REVIEW

**Review by FaGru3n — APPROVED** [review]
Thx @AngelikaWittek, LGTM

**Comment by SebastianBezold** [comment]
Hi @FaGru3n, since the description mentions UPCOMING changes, I think @AngelikaWittek should be the one to move the PR from "Draft" to "Ready for review".

**Comment by FaGru3n** [comment]
> Hi @FaGru3n, since the description mentions UPCOMING changes, I think @AngelikaWittek should be the one to move the PR from "Draft" to "Ready for review".

my bad sorry for that, but since all is written already we could allign on the date when we will merge the appoved PR... and added everyone within system team to inform everyone what will be the upcomming changes.

**Comment by AngelikaWittek** [comment]
Yes, it was intentionally put in the DRAFT state. Please do NOT merge!
There has to be some more work on the TRG7s and communicated with the committers.

**Review by SebastianBezold — APPROVED** [review]
LGTM. Also good template for others to follow

**Pull request merged**
